### PR TITLE
[#135] added warning on yaml tab for connections that credentials must be retyped

### LINKED ISSUE #135: add Note on YAML tab for connections that the user should retype credential fields
**Description**

There is no **Notice** or **Warning** for the user that the encrypted credentials (covered by "*****") must be retyped to submit the connection.

**Steps to Reproduce:**

1. Create connection.
2. Go to the YAML tab of the connection from step (1).
3. Notice that there is no note or warning that the user should retype the encrypted credentials (covered by "*****").

**Actual result**

There is no note that the user should retype the encrypted credentials.

**Expected result**

There is a note on the eye-catching place for the user that they should remember to retype the encrypted credentials.

**Attachments**

image

**Environment**

- ODAHU version: 1.6.0

### PR DESCRIPTION
**Pull request by YuraTyhun**

### CODE REVIEW

File: src/components/Editor.tsx [hunk 1]
```diff
@@ -70,8 +76,14 @@ export const Editor: React.FC<EditorProps | ReadonlyEditorProps> = (props) => {
 
     return (
         <>
+            {props?.warning && 
+                <div className={classes.warning}> 
+                    WARNING: To submit the connection please retype the encrypted credentials (covered by {'*****'}).
```
Comment (lev-titov) [inline src/components/Editor.tsx]: *optional*
```suggestion
                    WARNING: To submit edited connection please retype the encrypted credentials (covered by {'*****'}).
```

**Review by lev-titov — APPROVED** [review]

**Review by BPylypenko — APPROVED** [review]
